services:
  web:
    image: odoo:17.0
    container_name: {odoo_container_name}
    depends_on:
      - db
    ports:
      - "0.0.0.0:{odoo_port}:{odoo_port}"
      - "0.0.0.0:{gevent_port}:{gevent_port}"
    volumes:
      - ./config:/etc/odoo
      - ./volumes/odoo-data:/var/lib/odoo
      - ./enterprise:/mnt/enterprise
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
    entrypoint: []
    command: ["/usr/bin/odoo", "--workers=0", "--db_host=db", "--db_port={db_port}", "--db_user={db_user}", "--db_password={client_password}", "--database={odoo_db_name}", "--http-interface=0.0.0.0", "--gevent-port={gevent_port}", "--max-cron-threads=1"]
    environment:
      - HOST=db
      - PORT={db_port}
      - USER={db_user}
      - PASSWORD={client_password}
      - PGDATABASE={odoo_db_name}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: {db_container_name}
    command: ["postgres", "-c", "log_statement=none", "-c", "log_min_messages=warning", "-c", "log_min_error_statement=error"]
    environment:
      - POSTGRES_DB={odoo_db_name}
      - POSTGRES_PASSWORD={client_password}
      - PGDATABASE={odoo_db_name}
      - POSTGRES_USER={db_user}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data/pgdata
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: unless-stopped

volumes:
  odoo-data:
  postgres-data: